[package]
name = "rselisp-macros"
version = "0.1.0"
authors = ["Jean Pierre Dudey <jeandudey@hotmail.com>"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.11.11", features = ["full"] }
synom = "0.11.3"
quote = "0.3.15"

[dev-dependencies]
rselisp = { path = "../" }
